import { useState, useEffect, useLayoutEffect, useRef, useCallback, useId, useMemo } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { IconArrowLeft, IconArrowRight, IconBook2, IconPlus, IconPencil, IconDownload, IconHistory, IconTrash, IconCheck, IconX, IconSearch, IconChevronDown, IconMessageCircle, IconUser, IconRefresh } from '@tabler/icons-react';
import { Navbar, NavBody, MobileNav, MobileNavHeader, NavbarButton } from '../ui/resizable-navbar';
import { BentoGrid } from '../ui/bento-grid';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { useMembership } from '../membership/membership-context';
import { useAnalytics } from '../analytics';
import { membershipRequest, membershipApiUrl, formatMemberDate } from '../../lib/membership-api.mjs';
import { loadGuides, savePersonalGuide, exportPersonalGuide, validateGuide, isCurrentGuideOwner } from '../../lib/personal-guide-api.mjs';
import { validateQaResponse } from '../../lib/qa-response.mjs';
import { readerText } from '../../lib/reader-text.mjs';
import { guideExcerpt } from '../../lib/guide-excerpt.mjs';
import { entryLocationHref, guideLocationHref } from '../../lib/guide-location.mjs';
import { QaNotice } from '../qa-notice';
import { createGuideNavigationGuard, validatePersonalGuideCorpus, pendingGuideMessage } from '../../lib/personal-guide-navigation.mjs';

// Pending content lives only in mounted component state, never browser storage.
function usePendingChanges(scope, dirty, onPendingChange) {
  useLayoutEffect(() => { onPendingChange(scope, dirty); return () => onPendingChange(scope, false); }, [scope, dirty, onPendingChange]);
  return () => onPendingChange(scope, false);
}
const discardConfirmed = dirty => !dirty || window.confirm(pendingGuideMessage);
const base = import.meta.env.BASE_URL;
const sample = { title: '第一次租房，把该问的先问清楚', topic: '租房与买房', content: '## 先明确自己的需求\n预算、通勤、入住日期，都可以先写下来。\n\n## 签字前，逐项确认\n核对出租人身份、押金退还条件、维修责任，以及合同中的费用。重要约定写进合同，不只停留在口头。\n\n## 留下记录\n入住时拍照记录房屋现状。把合同、收据和沟通记录保存好。', tasks: [{ id: 'sample-1', title: '列出自己的租房预算和通勤要求', done: false }, { id: 'sample-2', title: '核对押金退还条件', done: false }], sourceIds: ['15-1'], factIds: [], revision: 1 };
const photoFor = topic => /工作|职|学习/.test(topic) ? 'scene-work' : /钱|省|财|消费/.test(topic) ? 'scene-money' : 'scene-home';

// Read-only rendering: text and headings only; raw HTML is never executed.
function GuideBody({ content }) {
  return <div className="personal-guide-body">{content.split(/\r?\n/).map((line, index) => {
    if (!line.trim()) return <div className="personal-guide-paragraph-gap" key={index}/>;
    const heading = line.match(/^(#{1,3})\s+(.+)$/);
    if (heading) return heading[1].length === 1 ? <h2 key={index}>{readerText(heading[2])}</h2> : <h3 key={index}>{readerText(heading[2])}</h3>;
    const list = line.match(/^\s*(?:[-*]|\d+[.)])\s+(.+)$/);
    return list ? <p className="personal-guide-bullet" key={index}><span aria-hidden="true">•</span>{readerText(list[1])}</p> : <p key={index}>{readerText(line)}</p>;
  })}</div>;
}

// Same inline expansion pattern as the Aceternity Expandable Card adaptation.
function Disclosure({ title, children, className = '' }) {
  const [open, setOpen] = useState(false), id = useId();
  return <section className={`personal-disclosure ${className}`}><NavbarButton as="button" type="button" variant="secondary" className="personal-disclosure-trigger" aria-expanded={open} aria-controls={id} onClick={() => setOpen(!open)}>{title}<IconChevronDown size={18} className={open ? 'is-open' : ''}/></NavbarButton><AnimatePresence initial={false}>{open && <motion.div id={id} initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: .2 }}><div className="personal-disclosure-content">{children}</div></motion.div>}</AnimatePresence></section>;
}

function SourceList({ sourceIds, corpus, sourceSnapshots = {}, snapshotDate }) {
  const entries = corpus?.chapters?.flatMap(chapter => chapter.entries.map(entry => ({ ...entry, chapterTitle: chapter.title, file: chapter.file }))) || [];
  return <Disclosure title={`原文依据${sourceIds.length ? ` · ${sourceIds.length} 条` : ''}`}><p className="personal-small-note">这些是书中依据，不是对你个人情况的独立核验。{(snapshotDate || corpus?.source?.snapshotDate) && <> 原文快照 {snapshotDate || corpus.source.snapshotDate}。</>}</p>{sourceIds.length ? <ul className="personal-source-list">{sourceIds.map(id => { const entry = entries.find(item => item.id === id), snapshot = sourceSnapshots[id]; return <li key={id}><IconBook2 size={16}/><span><a href={entry ? entryLocationHref(base, entry) : guideLocationHref(base, {})} target="_blank" rel="noopener noreferrer">{entry ? `${entry.chapterTitle} · ${readerText(snapshot?.title || entry.title)}` : snapshot?.title ? readerText(snapshot.title) : '打开指南核对原文'}</a>{snapshot?.snapshotDate && <small className="personal-source-date">关联时的原文快照：{snapshot.snapshotDate}</small>}</span></li>; })}</ul> : <p className="personal-small-note">这篇是你自己的笔记，还没有关联书中条目。</p>}</Disclosure>;
}

function ProfilePanel({ profile, onSaved, onPendingChange }) {
  const [editing, setEditing] = useState(false), [facts, setFacts] = useState([]), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const dirty = editing && JSON.stringify(facts) !== JSON.stringify(profile.facts.map(({ id, label, value }) => ({ id, label, value })));
  const clearPending = usePendingChanges('profile', dirty || busy, onPendingChange);
  const start = () => { setFacts(profile.facts.map(fact => ({ id: fact.id, label: fact.label, value: fact.value }))); setEditing(true); setError(''); };
  const save = async event => {
    event.preventDefault(); setBusy(true); setError('');
    try { const data = await membershipRequest('profile', { method: 'PATCH', body: { revision: profile.revision, facts } }); if (!Array.isArray(data.facts)) throw new Error('情况确认失败，请重试。'); clearPending(); onSaved(data); setEditing(false); }
    catch (e) { setError(e.status === 409 ? '你的个人情况在另一处更新了。请刷新后再确认，本次输入仍保留。' : e.message); }
    finally { setBusy(false); }
  };
  return <section className="personal-profile-panel"><div className="personal-section-top"><div><p className="eyebrow">ONLY WHAT YOU CONFIRM</p><h2>你确认过的个人情况</h2></div>{!editing && <NavbarButton as="button" type="button" className="outline-button" onClick={start}><IconPencil size={16}/>{profile.facts.length ? '编辑情况' : '添加情况'}</NavbarButton>}</div><p className="personal-small-note">只有你点“确认保存”的内容才会记录。继续提问时，你还可以选择本次要用哪几项。不需要填写身份证、住址或财务账号。</p>
    {editing ? <form onSubmit={save} className="personal-profile-form">{facts.map((fact, index) => <div className="personal-fact-edit" key={fact.id}><Input aria-label={`情况 ${index + 1} 的名称`} value={fact.label} placeholder="例如：工作情况" maxLength={80} required disabled={busy} onChange={e => setFacts(items => items.map(item => item.id === fact.id ? { ...item, label: e.target.value } : item))}/><textarea aria-label={`情况 ${index + 1} 的内容`} value={fact.value} placeholder="只写已经确认的情况，最多 500 字。不确定的先不写。" maxLength={500} required disabled={busy} onChange={e => setFacts(items => items.map(item => item.id === fact.id ? { ...item, value: e.target.value } : item))}/><NavbarButton as="button" type="button" variant="secondary" aria-label={`删除情况 ${index + 1}`} onClick={() => setFacts(items => items.filter(item => item.id !== fact.id))} disabled={busy}><IconX size={17}/></NavbarButton></div>)}<div className="personal-inline-actions"><NavbarButton as="button" type="button" className="outline-button" disabled={busy || facts.length >= 30} onClick={() => setFacts(items => [...items, { id: crypto.randomUUID(), label: '', value: '' }])}><IconPlus size={16}/> 添加一项</NavbarButton><NavbarButton as="button" type="submit" className="coral-button" disabled={busy}>{busy ? '正在确认……' : '确认保存这些情况'}</NavbarButton><NavbarButton as="button" type="button" variant="secondary" disabled={busy} onClick={() => { if (discardConfirmed(dirty)) { clearPending(); setEditing(false); } }}>取消</NavbarButton></div></form> : profile.facts.length ? <div className="personal-fact-list">{profile.facts.map(fact => <article key={fact.id}><span><IconCheck size={15}/> {fact.label}</span><p>{fact.value}</p><small>你于 {formatMemberDate(fact.confirmedAt)} 确认</small></article>)}</div> : <div className="personal-profile-empty"><IconUser size={25}/><p>还没有记录个人情况。<br/>先从一个真实问题开始，也完全可以。</p></div>}{error && <p className="member-error" role="alert">{error}</p>}</section>;
}

function VersionHistory({ guide, onSaved }) {
  const [versions, setVersions] = useState(null), [version, setVersion] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [confirm, setConfirm] = useState(false);
  const load = async () => { setBusy(true); setError(''); try { const data = await membershipRequest(`guides/${encodeURIComponent(guide.id)}/versions`); setVersions(data.versions || []); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const view = async id => { setBusy(true); setError(''); setConfirm(false); try { const data = await membershipRequest(`guides/${encodeURIComponent(guide.id)}/versions/${encodeURIComponent(id)}`); if (!data.version?.content && data.version?.content !== '') throw new Error('该版本暂时无法查看。'); setVersion(data.version); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const restore = async () => { setBusy(true); setError(''); try { const data = await membershipRequest(`guides/${encodeURIComponent(guide.id)}/restore`, { method: 'POST', body: { versionId: version.id, revision: guide.revision } }); onSaved(validateGuide(data.guide)); setVersion(null); setConfirm(false); setVersions(null); } catch (e) { setError(e.status === 409 ? '指南已在另一处更新，先刷新，再决定恢复哪个版本。' : e.message); } finally { setBusy(false); } };
  return <Disclosure title={<span><IconHistory size={17}/> 历史版本与撤回</span>}>{!versions ? <NavbarButton as="button" type="button" className="outline-button" onClick={load} disabled={busy}>{busy ? '正在读取……' : '查看历史版本'}</NavbarButton> : <><p className="personal-small-note">恢复会创建一个新版本，不会抹掉之前的记录。</p><div className="personal-version-list">{versions.map(item => <NavbarButton as="button" type="button" variant="secondary" key={item.id} onClick={() => view(item.id)} disabled={busy} aria-pressed={version?.id === item.id}><span>第 {item.revision} 版</span><small>{formatMemberDate(item.createdAt)}</small><IconArrowRight size={15}/></NavbarButton>)}</div></>}{version && <div className="personal-version-preview"><div className="personal-section-top"><h3>第 {version.revision} 版 · {version.title}</h3><NavbarButton as="button" type="button" variant="secondary" aria-label="关闭版本预览" onClick={() => setVersion(null)}><IconX size={17}/></NavbarButton></div><GuideBody content={version.content}/>{confirm ? <div className="personal-confirm-box"><p>用这一版恢复正文和任务记录？当前版本仍会留在历史中。</p><NavbarButton as="button" type="button" className="coral-button" onClick={restore} disabled={busy}>{busy ? '正在恢复……' : '确认恢复这一版'}</NavbarButton><NavbarButton as="button" type="button" variant="secondary" onClick={() => setConfirm(false)} disabled={busy}>先不恢复</NavbarButton></div> : <NavbarButton as="button" type="button" className="outline-button" onClick={() => setConfirm(true)} disabled={busy}>恢复这一版</NavbarButton>}</div>}{error && <p className="member-error" role="alert">{error}</p>}</Disclosure>;
}

function GuideEditor({ guide, profile, corpus, corpusLoading, onSaved, onBack, onDelete, onPendingChange }) {
  const { me, refresh, openAccount } = useMembership();
  const track = useAnalytics(), requestOwner = me?.user?.id || '', ownerRef = useRef(requestOwner);
  ownerRef.current = requestOwner;
  const [editing, setEditing] = useState(false), [values, setValues] = useState(guide), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [newTask, setNewTask] = useState(''), [deleteConfirm, setDeleteConfirm] = useState(false);
  const [question, setQuestion] = useState(''), [asking, setAsking] = useState(false), [answer, setAnswer] = useState(null), [draft, setDraft] = useState(null), [selectedFacts, setSelectedFacts] = useState(guide.factIds.filter(id => profile.facts.some(fact => fact.id === id))), [compare, setCompare] = useState(false);
  const controller = useRef(null), questionRequest = useRef(null), activeQuestion = useRef(null), mounted = useRef(true), id = useId();
  const editDirty = editing && ['title', 'topic', 'content'].some(key => values[key] !== guide[key]);
  const clearPending = usePendingChanges('editor', Boolean(editDirty || draft || newTask.trim() || question.trim() || busy || asking), onPendingChange);
  useEffect(() => { if (!editing) setValues(guide); }, [guide, editing]);
  useLayoutEffect(() => {
    mounted.current = true;
    return () => { mounted.current = false; activeQuestion.current?.abort.abort('unmounted'); activeQuestion.current = null; controller.current = null; };
  }, [requestOwner]);
  const save = async (next = values, draftConfirm = false) => {
    if (draftConfirm && next.baseRevision !== guide.revision) { setError('你在生成更新稿后修改过这篇指南。请保留当前版本，重新提问生成新稿，避免覆盖刚刚做过的修改。'); return false; }
    setBusy(true); setError(''); setNotice('');
    try { const result = await savePersonalGuide(guide.id, { revision: guide.revision, title: next.title, topic: next.topic, content: next.content, sourceIds: next.sourceIds, factIds: next.factIds.filter(factId => profile.facts.some(fact => fact.id === factId)), tasks: next.tasks }); clearPending(); onSaved(result); setEditing(false); if (draftConfirm) { setDraft(null); setAnswer(null); setQuestion(''); } setNotice(draftConfirm ? '更新稿已确认，已经成为你的新版本。' : '已保存。修改前的内容仍可以在历史版本里查看。'); return true; }
    catch (e) { setError(e.status === 409 ? '指南在另一处更新了。你的修改仍保留，先刷新核对，再重新保存。' : e.message); }
    finally { setBusy(false); }
  };
  const toggleTask = async task => { const next = { ...guide, tasks: guide.tasks.map(item => item.id === task.id ? { ...item, done: !item.done } : item) }; await save(next); };
  const addTask = async event => { event.preventDefault(); if (!newTask.trim() || busy) return; const next = { ...guide, tasks: [...guide.tasks, { id: crypto.randomUUID(), title: newTask.trim(), done: false }] }; if (await save(next)) setNewTask(''); };
  const download = async () => { setError(''); try { const blob = await exportPersonalGuide(guide.id); const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = `${guide.title.replace(/[<>:"/\\|?*]/g, '-')}.md`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e) { setError(e.message); } };
  const remove = async () => { setBusy(true); setError(''); try { const data = await membershipRequest(`guides/${encodeURIComponent(guide.id)}`, { method: 'DELETE' }); if (!data.ok) throw new Error('删除未完成，请重试。'); onDelete(guide.id); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const ask = async event => {
    event.preventDefault(); if (!question.trim() || asking || activeQuestion.current || !corpus || !requestOwner) return;
    if (draft && !window.confirm('当前更新稿还没有保存。重新提问会替换它，继续吗？')) return;
    setAsking(true); setError(''); setAnswer(null); setDraft(null); setNotice('');
    const key = `${guide.id}:${guide.revision}:${question.trim()}:${selectedFacts.join(',')}`;
    if (questionRequest.current?.key !== key) questionRequest.current = { key, id: crypto.randomUUID() };
    const abort = new AbortController(), request = { abort, owner: requestOwner }; controller.current = abort; activeQuestion.current = request;
    const isCurrent = () => mounted.current && activeQuestion.current === request && ownerRef.current === request.owner;
    // One fixed result per dispatched request; aborts finish immediately even if
    // a transport ignores cancellation. No account, guide, question or URL data.
    let reported = false;
    const report = outcome => { if (reported) return; reported = true; try { track('qa_result', { kind: 'personal', outcome }); } catch { /* Optional statistics cannot break asking. */ } };
    const onAbort = () => report('cancelled'); abort.signal.addEventListener('abort', onAbort, { once: true });
    const timer = setTimeout(() => abort.abort('timeout'), 60000);
    try {
      try { track('qa_submit', { kind: 'personal' }); } catch { /* Optional statistics cannot break asking. */ }
      const response = await fetch(membershipApiUrl(`guides/${encodeURIComponent(guide.id)}/ask`), { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: question.trim(), requestId: questionRequest.current.id, factIds: selectedFacts }), signal: abort.signal });
      if (!isCurrent()) return; abort.signal.throwIfAborted();
      const data = await response.json().catch(() => null);
      if (!isCurrent()) return; abort.signal.throwIfAborted();
      if (!response.ok) { if (response.status === 401) openAccount(); if (data?.error?.code !== 'request_pending') questionRequest.current = null; const failed = new Error(['request_released', 'request_expired'].includes(data?.error?.code) ? '上次回答未完成或已过期，本篇指南没有改动。现在可以重新提问。' : data?.error?.message || '这次提问未能完成，请重试。'); failed.status = response.status; throw failed; }
      const checked = validateQaResponse(data, corpus); report(checked.status === 'answered' ? 'success' : 'unavailable'); setAnswer(checked);
      if (checked.status === 'insufficient') questionRequest.current = null;
      if (checked.status !== 'insufficient' && data.draft && typeof data.draft.content === 'string' && Array.isArray(data.draft.tasks) && Array.isArray(data.draft.sourceIds)) setDraft({ ...guide, ...data.draft, baseRevision: guide.revision, factIds: [...selectedFacts], tasks: [...guide.tasks, ...data.draft.tasks.filter(task => !guide.tasks.some(item => item.id === task.id)).map(task => ({ ...task, done: false }))] });
      await refresh();
    } catch (e) { if (!isCurrent()) return; report(abort.signal.aborted ? 'cancelled' : 'error'); if (!abort.signal.aborted) setError(e instanceof TypeError ? '连接失败，请检查网络后重试。本篇指南没有被修改。' : e.message); else setError(abort.signal.reason === 'timeout' ? '回答等待太久，本篇指南没有被修改。可以重试。' : '已停止回答，本篇指南没有被修改。'); }
    finally { clearTimeout(timer); abort.signal.removeEventListener('abort', onAbort); if (activeQuestion.current === request) { activeQuestion.current = null; controller.current = null; if (mounted.current && ownerRef.current === request.owner) setAsking(false); } }
  };
  const completed = guide.tasks.filter(task => task.done).length;
  const goBack = () => onBack();
  const cancelEdit = () => { if (!discardConfirmed(editDirty)) return; setEditing(false); setValues(guide); };
  return <article className="personal-editor"><div className="personal-editor-top"><NavbarButton as="button" type="button" variant="secondary" onClick={goBack}><IconArrowLeft size={17}/> 我的指南目录</NavbarButton><span>{guide.topic || '生活'} · 更新于 {formatMemberDate(guide.updatedAt)}</span></div><div className="personal-editor-title"><p className="eyebrow">MY BETTER LIFE</p><h1 tabIndex={-1}>{readerText(guide.title)}</h1><p>第 {guide.revision} 版 · 由你确认，按自己的节奏完善。</p></div><div className="personal-inline-actions personal-editor-actions"><NavbarButton as="button" type="button" className="outline-button" disabled={busy || asking} onClick={() => { if (editing) cancelEdit(); else { setEditing(true); setValues(guide); } }}><IconPencil size={17}/>{editing ? '取消修改' : '编辑这篇指南'}</NavbarButton><NavbarButton as="button" type="button" className="outline-button" onClick={download}><IconDownload size={17}/> 导出到 Obsidian</NavbarButton></div>
    {error && <p className="member-error" role="alert">{error}</p>}{notice && <p className="personal-notice" role="status">{notice}</p>}
    <div className="personal-editor-layout"><div className="personal-editor-main">{editing ? <form className="personal-editor-form" onSubmit={event => { event.preventDefault(); save(); }}><Label htmlFor={`${id}-title`}>指南标题</Label><Input id={`${id}-title`} value={values.title} maxLength={120} required disabled={busy} onChange={event => setValues(value => ({ ...value, title: event.target.value }))}/><Label htmlFor={`${id}-topic`}>生活主题</Label><Input id={`${id}-topic`} value={values.topic} maxLength={80} disabled={busy} onChange={event => setValues(value => ({ ...value, topic: event.target.value }))}/><Label htmlFor={`${id}-content`}>正文 · 最多 12000 字，可以用 # 写小标题</Label><textarea id={`${id}-content`} value={values.content} maxLength={12000} disabled={busy} onChange={event => setValues(value => ({ ...value, content: event.target.value }))}/><div className="personal-inline-actions"><NavbarButton as="button" type="submit" className="coral-button" disabled={busy}>{busy ? '正在保存……' : '确认保存修改'}</NavbarButton><NavbarButton as="button" type="button" variant="secondary" disabled={busy} onClick={cancelEdit}>取消</NavbarButton></div></form> : <GuideBody content={guide.content}/>}<SourceList sourceIds={guide.sourceIds} corpus={corpus} sourceSnapshots={guide.sourceSnapshots} snapshotDate={guide.snapshotDate}/><VersionHistory guide={guide} onSaved={onSaved}/></div>
      <aside className="personal-action-panel"><div className="personal-action-heading"><IconCheck size={20}/><h2>把建议变成行动</h2></div><p className="personal-small-note">{completed} / {guide.tasks.length} 项已完成。只有你勾选的，才算完成。</p><div className="personal-task-progress" aria-hidden="true"><span style={{ width: `${guide.tasks.length ? completed / guide.tasks.length * 100 : 0}%` }}/></div>{guide.tasks.length ? <ul className="personal-tasks">{guide.tasks.map(task => <li key={task.id}><label><input type="checkbox" checked={task.done} disabled={busy || editing || asking} onChange={() => toggleTask(task)}/><span className={task.done ? 'task-done' : ''}>{task.title}</span></label></li>)}</ul> : <p className="personal-small-note">还没有行动项。可以写下一件你真正打算做的事。</p>}<form onSubmit={addTask} className="personal-add-task"><Input aria-label="新增行动项" value={newTask} onChange={e => setNewTask(e.target.value)} maxLength={300} placeholder="写下下一件小事" disabled={busy || editing || asking || guide.tasks.length >= 50}/><NavbarButton as="button" type="submit" variant="secondary" aria-label="添加行动项" disabled={busy || editing || asking || !newTask.trim() || guide.tasks.length >= 50}><IconPlus size={19}/></NavbarButton></form>
        <Disclosure title="本篇关联的个人情况">{guide.factIds.length ? profile.facts.filter(fact => guide.factIds.includes(fact.id)).map(fact => <div className="personal-linked-fact" key={fact.id}><b>{fact.label}</b><p>{fact.value}</p></div>) : <p className="personal-small-note">没有关联个人情况。不必为了完善指南而填写额外信息。</p>}</Disclosure>
      </aside></div>
    <section className="personal-continue"><div className="personal-section-top"><div><p className="eyebrow">KEEP MAKING IT YOURS</p><h2><IconMessageCircle size={24}/> 后来又遇到了什么？</h2><p>带着这篇指南继续问。新回答会先成为更新稿，等你确认后才保存。</p></div></div>{!corpus && <p className="personal-small-note" role="status">{corpusLoading ? '正在读取书中原文，完成后就可以继续提问。' : '先重新加载书中原文，就可以继续提问；你的指南仍可编辑和导出。'}</p>}<form onSubmit={ask}><Label htmlFor={`${id}-question`}>你的新问题</Label><textarea id={`${id}-question`} value={question} onChange={e => setQuestion(e.target.value)} placeholder="例如：我已经跟房东沟通过了，但对方还没有回复，下一步怎么办？" maxLength={500} required disabled={asking || busy || editing}/>{profile.facts.length > 0 && <Disclosure title={`本次使用的已确认情况 · ${selectedFacts.length} 项`}><p className="personal-small-note">按需选择，最多 8 项。未选中的情况不会发送给模型。</p><div className="personal-fact-options">{profile.facts.map(fact => <label key={fact.id}><input type="checkbox" checked={selectedFacts.includes(fact.id)} disabled={asking || (!selectedFacts.includes(fact.id) && selectedFacts.length >= 8)} onChange={() => setSelectedFacts(ids => ids.includes(fact.id) ? ids.filter(id => id !== fact.id) : [...ids, fact.id])}/><span><b>{fact.label}</b><small>{fact.value}</small></span></label>)}</div></Disclosure>}<div className="personal-inline-actions"><NavbarButton as="button" type="submit" className="coral-button" disabled={asking || busy || editing || !corpus}>{asking ? '正在结合原文整理……' : '继续完善这篇指南'}<IconArrowRight size={18}/></NavbarButton>{asking && <NavbarButton as="button" type="button" variant="secondary" onClick={() => controller.current?.abort()}>停止回答</NavbarButton>}<span className="personal-small-note">成功回答扣 1 次，不会自动保存。</span></div></form>
      {answer && <div className="personal-new-answer"><p className="personal-answer-label">{answer.status === 'insufficient' ? '书中依据不足 · 原指南没有修改' : '这次的新建议'}</p><p>{readerText(answer.answer.intro)}</p>{answer.answer.steps?.map((step, index) => <div key={index}><h3>{index + 1}. {readerText(step.title)}</h3><p>{readerText(step.detail)}</p></div>)}<QaNotice value={answer.answer.caveat}/><SourceList sourceIds={answer.sources.map(source => source.id)} corpus={corpus}/></div>}
      {draft && <div className="personal-draft"><div className="personal-section-top"><div><p className="eyebrow">WAITING FOR YOUR CONFIRMATION</p><h2>这是一份更新稿，不是已保存的指南。</h2></div></div><p className="personal-small-note">你可以改正文，再确认。已有任务的完成状态不会被 AI 更改；新任务也不会被自动勾选。</p><Label htmlFor={`${id}-draft`}>待确认的新正文</Label><textarea id={`${id}-draft`} value={draft.content} maxLength={12000} disabled={busy} onChange={e => setDraft(value => ({ ...value, content: e.target.value }))}/><NavbarButton as="button" type="button" variant="secondary" className="personal-compare-toggle" aria-expanded={compare} onClick={() => setCompare(!compare)}>{compare ? '收起原正文' : '对照目前保存的正文'}<IconChevronDown size={16}/></NavbarButton>{compare && <div className="personal-original-preview"><GuideBody content={guide.content}/></div>}<div className="personal-draft-tasks"><b>更新后的行动项</b>{draft.tasks.map(task => <p key={task.id}>{task.done ? '已完成' : '待行动'} · {task.title}</p>)}</div><div className="personal-inline-actions"><NavbarButton as="button" type="button" className="coral-button" disabled={busy || asking} onClick={() => save(draft, true)}>{busy ? '正在保存……' : '确认采用更新稿'}<IconCheck size={18}/></NavbarButton><NavbarButton as="button" type="button" className="outline-button" disabled={busy} onClick={() => { if (discardConfirmed(Boolean(draft))) { setDraft(null); setNotice('已放弃更新稿，原指南保持不变。'); } }}>保留原稿，放弃更新</NavbarButton></div></div>}
    </section><section className="personal-delete-section">{deleteConfirm ? <div className="personal-confirm-box"><p>确定删除“{guide.title}”？正文、行动记录和历史版本都会删除。建议先导出一份。</p><NavbarButton as="button" type="button" className="outline-button personal-danger-button" onClick={remove} disabled={busy}>确认删除这篇指南</NavbarButton><NavbarButton as="button" type="button" variant="secondary" onClick={() => setDeleteConfirm(false)} disabled={busy}>保留这篇</NavbarButton></div> : <NavbarButton as="button" type="button" variant="secondary" onClick={() => setDeleteConfirm(true)} className="personal-delete-button"><IconTrash size={16}/> 删除这篇指南</NavbarButton>}</section>
  </article>;
}

function NewGuideForm({ onCreated, onCancel, onPendingChange }) {
  const [title, setTitle] = useState(''), [topic, setTopic] = useState(''), [content, setContent] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const id = useId();
  const clearPending = usePendingChanges('new', Boolean(title.trim() || topic.trim() || content.trim() || busy), onPendingChange);
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const guide = await savePersonalGuide(null, { title: title.trim(), topic: topic.trim() || '生活', content, sourceIds: [], factIds: [], tasks: [] }); clearPending(); onCreated(guide); } catch (error) { setError(error.message); } finally { setBusy(false); } };
  return <section className="personal-create-panel"><div className="personal-section-top"><h2>从一篇自己的笔记开始。</h2><NavbarButton as="button" type="button" variant="secondary" aria-label="关闭新建指南" disabled={busy} onClick={onCancel}><IconX size={20}/></NavbarButton></div><form onSubmit={submit} className="personal-editor-form"><Label htmlFor={`${id}-title`}>指南标题</Label><Input id={`${id}-title`} value={title} placeholder="例如：我的租房避坑清单" maxLength={120} required disabled={busy} onChange={e => setTitle(e.target.value)}/><Label htmlFor={`${id}-topic`}>生活主题</Label><Input id={`${id}-topic`} value={topic} placeholder="例如：租房与买房" maxLength={80} disabled={busy} onChange={e => setTopic(e.target.value)}/><Label htmlFor={`${id}-content`}>你想留下的内容</Label><textarea id={`${id}-content`} value={content} placeholder="先写下一点，就比只想不做更近一步。" maxLength={12000} disabled={busy} onChange={e => setContent(e.target.value)}/><NavbarButton as="button" type="submit" className="coral-button" disabled={busy}>{busy ? '正在保存……' : '创建我的指南'}<IconPlus size={18}/></NavbarButton></form>{error && <p className="member-error" role="alert">{error}</p>}</section>;
}

export function PersonalGuidePage({ corpus: suppliedCorpus }) {
  const { me, loading: memberLoading, status, openAccount } = useMembership();
  const [data, setData] = useState(null), [profile, setProfile] = useState({ facts: [], revision: 0 }), [corpus, setCorpus] = useState(suppliedCorpus || null), [loading, setLoading] = useState(false), [error, setError] = useState(''), [selected, setSelected] = useState(() => new URLSearchParams(location.search).get('guide') || ''), [query, setQuery] = useState(''), [topic, setTopic] = useState(''), [tab, setTab] = useState('guides'), [creating, setCreating] = useState(false), [showSample, setShowSample] = useState(false);
  const [dataOwner, setDataOwner] = useState(null), [corpusError, setCorpusError] = useState(''), [corpusLoading, setCorpusLoading] = useState(!suppliedCorpus), [corpusRetry, setCorpusRetry] = useState(0);
  const controller = useRef(null), userId = me?.user?.id, userIdRef = useRef(userId), pending = useRef(new Map()), navigation = useRef(null);
  const onPendingChange = useCallback((scope, dirty) => { const key = `${userId}:${scope}`; if (dirty) pending.current.set(key, true); else pending.current.delete(key); }, [userId]);
  const canLeave = () => navigation.current?.confirmLeave() ?? true;
  const ownedData = dataOwner === userId ? data : null;
  userIdRef.current = userId;
  const reload = useCallback(async () => {
    if (!userId) return;
    controller.current?.abort(); const abort = new AbortController(); controller.current = abort; setLoading(true); setError('');
    try { const [guides, facts] = await Promise.all([loadGuides({ signal: abort.signal }), membershipRequest('profile', { signal: abort.signal })]); if (!isCurrentGuideOwner(userIdRef.current, userId, abort.signal)) return; if (!Array.isArray(facts.facts)) throw new Error('个人情况暂时无法读取。'); setDataOwner(userId); setData(guides); setProfile(facts); }
    catch (e) { if (e.name !== 'AbortError' && isCurrentGuideOwner(userIdRef.current, userId, abort.signal)) setError(e.message); }
    finally { if (isCurrentGuideOwner(userIdRef.current, userId, abort.signal)) setLoading(false); }
  }, [userId]);
  useEffect(() => { setData(null); setDataOwner(null); setProfile({ facts: [], revision: 0 }); setShowSample(false); setCreating(false); setTab('guides'); setQuery(''); setTopic(''); pending.current.clear(); if (userId) reload(); return () => controller.current?.abort(); }, [userId, reload]);
  useEffect(() => {
    const abort = new AbortController(); setCorpusError(''); setCorpusLoading(true);
    const load = suppliedCorpus ? Promise.resolve(suppliedCorpus) : fetch(`${base}content.json`, { signal: abort.signal }).then(response => { if (!response.ok) throw new Error('书中原文暂时没有加载成功。'); return response.json(); });
    load.then(validatePersonalGuideCorpus).then(value => { if (!abort.signal.aborted) setCorpus(value); }).catch(() => { if (!abort.signal.aborted) { setCorpus(null); setCorpusError('书中原文暂时没有加载成功。你的指南还在，可以继续编辑、导出和查看已保存的来源信息。'); } }).finally(() => { if (!abort.signal.aborted) setCorpusLoading(false); });
    return () => abort.abort();
  }, [suppliedCorpus, corpusRetry]);
  useEffect(() => {
    const guard = createGuideNavigationGuard({ window, hasPending: () => [...pending.current.keys()].some(key => key.startsWith(`${userIdRef.current}:`)), onNavigate: url => { setSelected(new URL(url).searchParams.get('guide') || ''); setCreating(false); } });
    navigation.current = guard;
    return () => { guard.dispose(); navigation.current = null; };
  }, []);
  const openGuide = (guideId, confirmed = false) => { const params = new URLSearchParams(location.search); params.set('view', 'guides'); if (guideId) params.set('guide', guideId); else params.delete('guide'); if (!navigation.current?.push(`${location.pathname}?${params}`, { confirmed })) return; window.scrollTo({ top: 0, behavior: 'instant' }); requestAnimationFrame(() => document.querySelector('.personal-editor-title h1')?.focus({ preventScroll: true })); };
  const changed = guide => { if (!isCurrentGuideOwner(userIdRef.current, userId)) return; setData(value => value && isCurrentGuideOwner(userIdRef.current, userId) ? ({ ...value, guides: [guide, ...value.guides.filter(item => item.id !== guide.id)], remaining: Math.max(0, value.limit - (value.guides.some(item => item.id === guide.id) ? value.guides.length : value.guides.length + 1)) }) : value); };
  const created = guide => { if (!isCurrentGuideOwner(userIdRef.current, userId)) return; changed(guide); openGuide(guide.id, true); };
  const deleted = guideId => { if (!isCurrentGuideOwner(userIdRef.current, userId)) return; setData(value => { if (!value || !isCurrentGuideOwner(userIdRef.current, userId)) return value; const guides = value.guides.filter(item => item.id !== guideId); return { ...value, guides, remaining: Math.max(0, value.limit - guides.length) }; }); openGuide('', true); };
  const profileSaved = value => { if (isCurrentGuideOwner(userIdRef.current, userId)) setProfile(current => isCurrentGuideOwner(userIdRef.current, userId) ? value : current); };
  const guides = ownedData?.guides || [], active = guides.find(guide => guide.id === selected), topics = [...new Set(guides.map(guide => guide.topic || '生活'))], found = useMemo(() => guides.filter(guide => (!topic || (guide.topic || '生活') === topic) && `${guide.title} ${guide.content} ${guide.topic}`.toLowerCase().includes(query.trim().toLowerCase())), [guides, topic, query]);
  const completed = guides.reduce((n, guide) => n + guide.tasks.filter(task => task.done).length, 0), tasks = guides.reduce((n, guide) => n + guide.tasks.length, 0);
  const brand = <a className="brand" href={base}><img src={`${base}media/brand.webp`} width="40" height="40" alt=""/><span><b>BETTER LIFE</b><small>高性价比人生指南</small></span></a>;
  const actions = <div className="pricing-nav-actions"><NavbarButton href={base} variant="secondary" className="pricing-home-link"><IconArrowLeft size={17}/> 回到指南</NavbarButton><NavbarButton as="button" type="button" className="outline-button" onClick={openAccount}><IconUser size={17}/>{me?.user ? '我的会员' : '登录'}</NavbarButton></div>;
  return <div className="personal-page"><a className="skip-link" href="#personal-content">跳到我的指南</a><Navbar className="site-navbar pricing-navbar fixed top-0"><NavBody className="desktop-nav">{brand}{actions}</NavBody><MobileNav><MobileNavHeader>{brand}{actions}</MobileNavHeader></MobileNav></Navbar><main id="personal-content" className="page-width">{corpusError && <div className="personal-corpus-error" role="alert"><p>{corpusError}</p><NavbarButton as="button" type="button" className="outline-button" onClick={() => setCorpusRetry(value => value + 1)} disabled={corpusLoading}><IconRefresh size={18}/>{corpusLoading ? '正在加载……' : '重新加载原文'}</NavbarButton></div>}
    {memberLoading && !me ? <p className="personal-page-loading" role="status">正在读取账号……</p> : !userId ? <><header className="personal-directory-hero"><div><p className="eyebrow">MY BETTER LIFE</p><h1>好建议很多。<br/><span>这一份，属于你。</span></h1><p>把问题、下一步和已经做过的事，<br/>整理成自己的高性价比人生指南。</p><div className="personal-inline-actions"><NavbarButton as="button" type="button" className="coral-button" onClick={openAccount}>登录，开始我的指南<IconArrowRight size={18}/></NavbarButton><NavbarButton as="button" type="button" className="outline-button" onClick={() => setShowSample(!showSample)}>{showSample ? '收起样例' : '先看看长什么样'}</NavbarButton></div>{!status.loginAvailable && <p className="personal-login-note">邮箱登录暂未开放。下面的样例仅演示形式，不是你的个人档案。</p>}</div><div className="personal-hero-photo"><img src={`${base}media/scene-work.webp`} alt="阳光下的桌面、笔记本和咖啡"/><span>从一条建议开始，<br/>慢慢过成自己的生活。</span></div></header>{showSample && <section className="personal-sample"><span className="personal-sample-badge">只读样例 · 不是你的个人档案</span><h2>{sample.title}</h2><GuideBody content={sample.content}/><h3>可以记录的行动</h3>{sample.tasks.map(task => <p className="personal-sample-task" key={task.id}><span aria-hidden="true">□</span>{task.title}</p>)}<SourceList sourceIds={sample.sourceIds} corpus={corpus}/><p className="personal-small-note">样例没有为你建立账号、确认任何个人事实，或创建实际记录。</p></section>}<section className="personal-guest-explainer"><div><IconBook2 size={24}/><h2>你的主题目录</h2><p>工作、住房、省钱，按自己的生活整理。</p></div><div><IconCheck size={24}/><h2>你确认过的行动</h2><p>做到了再勾选。不是 AI 替你完成。</p></div><div><IconHistory size={24}/><h2>可以反悔的更新</h2><p>新稿先确认，旧稿有历史，可以导出。</p></div></section></> : (!ownedData && !error) || loading && !ownedData ? <p className="personal-page-loading" role="status">正在打开你自己的目录……</p> : error && !ownedData ? <div className="personal-load-error"><h1>暂时打不开你的目录。</h1><p role="alert">{error}</p><NavbarButton as="button" type="button" className="outline-button" onClick={reload}><IconRefresh size={18}/> 重新读取</NavbarButton></div> : active ? <GuideEditor key={`${userId}:${active.id}`} guide={active} profile={profile} corpus={corpus} corpusLoading={corpusLoading} onPendingChange={onPendingChange} onSaved={changed} onBack={() => openGuide('')} onDelete={deleted}/> : <>
      <header className="personal-directory-hero"><div><p className="eyebrow">MY BETTER LIFE</p><h1>我的高性价比<br/><span>人生指南。</span></h1><p>每一次认真提问，<br/>都值得变成一份自己的生活笔记。</p><div className="personal-real-stats"><span><b>{guides.length}</b> 篇自己的指南</span><span><b>{completed}<small> / {tasks}</small></b> 项行动已完成</span></div><div className="personal-inline-actions"><NavbarButton as="button" type="button" className="coral-button" disabled={!data || data.remaining <= 0} onClick={() => { if (!creating && canLeave()) { setCreating(true); setTab('guides'); } }}><IconPlus size={18}/> 新建自己的指南</NavbarButton><NavbarButton href={base} className="outline-button">也可以先问一个问题<IconArrowRight size={17}/></NavbarButton></div></div><div className="personal-hero-photo"><img src={`${base}media/scene-work.webp`} alt="桌上的笔记本与咖啡，留出一段整理生活的时间"/><span>从今天开始，<br/>把好建议真正用起来。</span></div></header>
      <div className="personal-directory-tabs"><NavbarButton as="button" type="button" variant="secondary" aria-pressed={tab === 'guides'} onClick={() => { if (tab !== 'guides' && canLeave()) setTab('guides'); }}><IconBook2 size={17}/> 我的指南目录</NavbarButton><NavbarButton as="button" type="button" variant="secondary" aria-pressed={tab === 'profile'} onClick={() => { if (tab !== 'profile' && canLeave()) { setTab('profile'); setCreating(false); } }}><IconUser size={17}/> 我确认过的情况</NavbarButton><span>已保存 {guides.length} / {data?.limit || 0} 篇</span></div>{error && <p className="member-error" role="alert">{error}</p>}{selected && !active && <p className="personal-small-note" role="status">这篇指南不存在，或不属于当前账号。下面只显示你自己的目录。</p>}
      {tab === 'profile' ? <ProfilePanel key={userId} profile={profile} onSaved={profileSaved} onPendingChange={onPendingChange}/> : <>{creating && <NewGuideForm key={userId} onCreated={created} onPendingChange={onPendingChange} onCancel={() => { if (canLeave()) setCreating(false); }}/>}<div className="personal-directory-controls"><div className="personal-search"><IconSearch size={19}/><Input aria-label="搜索我的指南" placeholder="在自己的指南里找一找……" value={query} onChange={e => setQuery(e.target.value)}/></div><select aria-label="按生活主题筛选" value={topic} onChange={e => setTopic(e.target.value)}><option value="">全部生活主题</option>{topics.map(value => <option key={value} value={value}>{value} · {guides.filter(guide => (guide.topic || '生活') === value).length} 篇</option>)}</select></div>
        {found.length ? <BentoGrid className="personal-directory-grid">{found.map(guide => <motion.article key={guide.id} className="personal-guide-card" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><button type="button" onClick={() => openGuide(guide.id)} aria-label={`打开指南：${guide.title}`}><div className="personal-card-photo"><img src={`${base}media/${photoFor(guide.topic)}.webp`} alt="" loading="lazy"/><span>{guide.topic || '生活'}</span></div><div className="personal-card-content"><h2>{readerText(guide.title)}</h2><p>{guideExcerpt(guide.content) || '从一段自己的生活记录开始。'}</p><div><span>{guide.tasks.filter(task => task.done).length} / {guide.tasks.length} 项完成</span><small>{formatMemberDate(guide.updatedAt)}</small><IconArrowRight size={17}/></div></div></button></motion.article>)}</BentoGrid> : <section className="personal-directory-empty"><IconBook2 size={34}/><h2>{guides.length ? '暂时没有找到这篇。' : '还没有自己的指南，刚好从今天开始。'}</h2><p>{guides.length ? '试试更短的词，或换一个主题。' : '先问一个你正在遇到的问题，把有用的回答留下来。也可以从一篇自己的笔记开始。'}</p><NavbarButton href={base} className="coral-button">去问第一个问题<IconArrowRight size={18}/></NavbarButton></section>}
        {data?.remaining <= 0 && <p className="personal-limit-note">当前套餐可保存的篇数已用完。已有指南仍可以编辑、导出和删除。<a href={`${base}?view=pricing`}>了解会员</a></p>}</>}
    </>}
    </main><footer className="page-width pricing-footer"><div><b>BETTER LIFE</b><p>建议来自指南。生活，由你自己确认。</p></div><a href={`${base}?view=pricing`} className="source-link">会员与价格</a><a href={`${base}content-source.html`} className="source-link">内容来源</a></footer></div>;
}
